image: docker:latest

services:
- docker:dind

stages:
- build
- test
- deploy

before_script:
- docker info
- apk update
- apk upgrade
- apk add git python python-dev py-pip build-base
- pip install docker-compose

build:
  stage: build
  script: make splunk

test:
  stage: test
  script:
  - pip install -r tests/requirements.txt
  - pytest -sv tests/test_debian_9.py::TestDebian9::test_splunk_entrypoint_help --junitxml testresults.xml
  - ls -al
  artifacts:
    reports:
      junit: testresults.xml
      
deploy:
  stage: deploy
  script: echo "Reached deploy step, pipeline done"

